application: blorgmusic
version: 5
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /parsesongdata/*
  script: BlorgMusicIngestPipeline/parsesongdata.py

- url: .*
  script: main.py

